### ISSUE TITLE
Generating logs, please wait

### ISSUE THREAD

**Issue by dannymichel** [brandons209/Script-Generator-Cog#20]
All I'm getting is ``Generating logs, please wait``. It doesnt say it's done or that i can download them and i dont see them on my dedicated server in the files.

**Comment by brandons209** [comment]
If nothing comes up then that means it didn't find any logs you were looking for

Make sure data exists for what you are looking for. I'll add an error message when there is no data so its more clear.

**Comment by dannymichel** [comment]
> If nothing comes up then that means it didn't find any logs you were looking for
> 
> Make sure data exists for what you are looking for. I'll add an error message when there is no data so its more clear.

was my fault. i didnt turn logging on.
but what sucks is that it doesnt get audit logs retroactively(or before you installed the cog) which im thinking it should since audit logs just exist

**Comment by brandons209** [comment]
well i can maybe try to add add a feature where itll get all audit logs and save then when you first install the cog. but the logs you get are from what it saves so by design it won't have anything until you install it
