### ISSUE TITLE
Personalroles auto issue 

### ISSUE THREAD

**Issue by Majesty01** [brandons209/Script-Generator-Cog#21]
Trying to set the myrole auto but the bot gives error saying role not found but the role exists.

Command used: !myrole auto roles @Donator

"warning These roles weren't found, please try again: @Donator

**Comment by brandons209** [comment]
Hey! I haven't upgraded the syntax to be easier to use. You need to use a comma separated list of role names or role ids. So remove the @ and just use the role name, and it should work.

I'll update this in the future to be more like other cogs which can take role names, ids, and mentions.

**Comment by brandons209** [comment]
If you still have questions feel free to reopen the issue.
