### ISSUE TITLE
personalroles error

### ISSUE THREAD

**Issue by Majesty01** [brandons209/Script-Generator-Cog#23]
Personalroles **!myrole auto roles** command does not work.
I have tried with role id, pinging the role, just the role name.

It says role doesn't exist when it clearly does.

**Comment by brandons209** [comment]
Alright, will look into this, I was planning on fixing the way it parses the roles to something more standard anyways.

**Comment by brandons209** [comment]
9540c3c6528472f4e9f7647202bbcbaa0d4033f9 should fix it. Its not longer a comma separated list, and role mentions, ids, and names should all work.

**Comment by brandons209** [comment]
I am closing this, assuming this fixed the issue. Feel free to reopen if you are still having an issue.
